### ISSUE TITLE
Remove need to patch logging in skycoin lib

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-lite#17]
https://github.com/skycoin/skycoin/pull/1611

src/util/logging has been removed from the coin package, so we shouldn't need to fixup the vendor skycoin coin package anymore

**Comment by Senyoret1** [comment]
The change made to the node reduced the number of dependencies, but the problem continues. Before the change, grep indicated that the dependency was in these places:
![grep2](https://user-images.githubusercontent.com/34079003/40997624-582c2724-68d3-11e8-9bee-9dd0f08fca4f.png)
After the change the result is this:
![grep1](https://user-images.githubusercontent.com/34079003/40997642-6664648c-68d3-11e8-8bec-cef40d5517c2.png)
When trying to compile the problem is the same:
![grep3](https://user-images.githubusercontent.com/34079003/40997704-8f975814-68d3-11e8-8606-1e07a6a149a0.png)

**Comment by gz-c** [comment]
Ok, need to do https://github.com/skycoin/skycoin/issues/1633 too

**Comment by gz-c** [comment]
@Senyoret1 `util/logging` is removed from `cipher` now
